[theme]
primaryColor = "#0069B4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F3F5"
textColor = "#1F1F1F"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
